### ISSUE TITLE
Download for resource gfw_lossyear failed. Returning unmodified portfolio object. 

### ISSUE THREAD

**Issue by APAF13** [mapme-initiative/mapme.biodiversity#102]
Bonjour,

Je n'arrive pas à télécharger les indicateurs "gfw_lossyear","gfw_treecover","gfw_emissions" compris dans le package mapme... Les fichiers de chaque indicateur apparaissent dans mes files mais vides "O B". 
Savez-vous à quoi cela est dû? 

**Voici mes codes :** 

library(mapme.biodiversity)
library(sf)
library(tidyverse)
library(mapview)

# load data
afd<-read_sf("C:/Users/POULINL/Documents/Aires protégées/BDD_SHP_nodupl.shp")

# View data
mapView(afd)

# preprocess: transform multipolygon geometries to single polygon geometries
afd<-sf::st_cast(afd,to="POLYGON")

# initialize portfolio
afd_portfolio <- afd %>%
  init_portfolio(2000:2020,
                 cores = 1,
                 verbose = TRUE)

# ----- Forest Area -----
# download relevant data ressources and link them to the portfolio
afd_portfolio<-
  get_resources(afd_portfolio,
                resources = c("gfw_lossyear","gfw_treecover","gfw_emissions"), 
                vers_treecover = "GFC-2020-v1.8",
                vers_lossyear = "GFC-2020-v1.8"
  )

**Voici le message d'erreur que j'obtiens :** 

Starting process to download resource 'gfw_lossyear'........
  |                                                  | 0 % ~calculating  
<simpleWarning in download.file(missing_urls[i], missing_filenames[i], quiet = TRUE,     "libcurl", mode = ifelse(Sys.info()["sysname"] == "Windows",         "wb", "w")): URL 'https://storage.googleapis.com/earthenginepartners-hansen/GFC-2020-v1.8/Hansen_GFC-2020-v1.8_lossyear_20N_000E.tif': Timeout of 600 seconds was reached>
Starting process to download resource 'gfw_treecover'........
  |                                                  | 0 % ~calculating  
<simpleWarning in download.file(missing_urls[i], missing_filenames[i], quiet = TRUE,     "libcurl", mode = ifelse(Sys.info()["sysname"] == "Windows",         "wb", "w")): URL 'https://storage.googleapis.com/earthenginepartners-hansen/GFC-2020-v1.8/Hansen_GFC-2020-v1.8_treecover2000_20N_000E.tif': Timeout of 600 seconds was reached>
Starting process to download resource 'gfw_emissions'........
  |                                                  | 0 % ~calculating  
<simpleWarning in download.file(missing_urls[i], missing_filenames[i], quiet = TRUE,     "libcurl", mode = ifelse(Sys.info()["sysname"] == "Windows",         "wb", "w")): URL 'https://data-api.globalforestwatch.org/dataset/gfw_forest_carbon_gross_emissions/v20211022/download/geotiff?grid=10/40000&tile_id=00N_000E&pixel_meaning=Mg_CO2e_px&x-api-key=2d60cd88-8348-4c0f-a6d5-bd9adb585a8c': Timeout of 600 seconds was reached>
Warning messages:
1: Download for resource gfw_lossyear failed. Returning unmodified portfolio object. 
2: Download for resource gfw_treecover failed. Returning unmodified portfolio object. 
3: Download for resource gfw_emissions failed. Returning unmodified portfolio object. 

Merci beaucoup pour votre aide

**Comment by goergen95** [comment]
Thanks for reporting the issue. I will reply in English I hope that is fine with you. There seems to be an issue with download.file on windows. Could you please run  `capabilities("libcurl")` and paste the output here? Additionally, are you running the code behind a proxy?

**Comment by APAF13** [comment]
Thank you for replying.

I was indeed running the code behind a proxy servir. I tried it on my own computer and it partially succedeed but there is still a big issue in dowloading 2 indicators : 

> afd_portfolio<-
+   get_resources(afd_portfolio,
+     resources = c("gfw_lossyear","gfw_treecover","gfw_emissions"), 
+     vers_treecover = "GFC-2020-v1.8",
+     vers_lossyear = "GFC-2020-v1.8"
+   )
Starting process to download resource 'gfw_lossyear'........
  |++++++++++++++++++++++++++++++++++++++++++++++++++| 100% elapsed=08m 04s
Starting process to download resource 'gfw_treecover'........
  |+++++++++++++++++++++++++++++++++++++++++         | 81% ~10m 37s      
<simpleWarning in download.file(missing_urls[i], missing_filenames[i], quiet = TRUE,     "libcurl", mode = ifelse(Sys.info()["sysname"] == "Windows",         "wb", "w")): taille téléchargée 163822357 != taille déclarée 343929911>
Starting process to download resource 'gfw_emissions'........
  |++++++++                                          | 15% ~21m 24s      
<simpleWarning in download.file(missing_urls[i], missing_filenames[i], quiet = TRUE,     "libcurl", mode = ifelse(Sys.info()["sysname"] == "Windows",         "wb", "w")): taille téléchargée 164777547 != taille déclarée 196002923>
Messages d'avis :
**1: Download for resource gfw_treecover failed. Returning unmodified portfolio object. 
2: Download for resource gfw_emissions failed. Returning unmodified portfolio object.** 


Otherwise, I ran : capabilities("libcurl") and got : 
libcurl 
   TRUE 


Thank you very much for your help

**Comment by APAF13** [comment]
Thank you for replying.

I was indeed running the code behind a proxy servir. I tried it on my own computer and it partially succedeed but there is still an issue in dowloading the gfw_emissions indicator :

"> afd_portfolio<-
+   get_resources(afd_portfolio,
+     resources = c("gfw_lossyear","gfw_treecover","gfw_emissions"), 
+     vers_treecover = "GFC-2020-v1.8",
+     vers_lossyear = "GFC-2020-v1.8"
+   )

**The following requested resources are already available: gfw_lossyear, gfw_treecover.**
Starting process to download resource 'gfw_emissions'........
Skipping existing files in output directory.
**Erreur : [rast] cannot open this file as a SpatRaster: /Users/lea/gfw_emissions/gfw_forest_carbon_gross_emissions_Mg_CO2e_px_40N_100E.tif
De plus : Message d'avis :
`/Users/lea/gfw_emissions/gfw_forest_carbon_gross_emissions_Mg_CO2e_px_40N_100E.tif' not recognized as a supported file format. (GDAL error 4) "**


Otherwise, I ran : capabilities("libcurl") and got :
libcurl
TRUE

Thank you very much for your help

**Comment by goergen95** [comment]
Sorry for the inconveniences, now it seems that  one gfw_emission raster was only partially downloaded thus opening it fails. Please consider deleting the gfw_emission directory and re-run the code. With R's internal download utility we currently cannot check if a file was downloaded completely.

As an alternative you can also point `aria_bin` to the path of an aria executable when initializing a portfolio. This would come with the benefit of resuming partial downloads and parallel downloads as well. To use this please install the [aria](https://github.com/aria2/aria2/releases/tag/release-1.36.0) executable for your system.

**Comment by APAF13** [comment]
Thank you, it worked well (my portfolio has been initialized)!

I'm now trying to calculate some indicators such as mangroves area evolution with these codes :

# ----- Mangrove Area -----
# download relevant data
afd_portfolio2<-
  get_resources(afd_portfolio,
                resources = c("gmw")
  )

# calculate indicators
afd_portfolio2<-
  calc_indicators(x = afd_portfolio2,
                  indicators = "mangroves_area",
                  overwrite=T)

# unnest results data for further analysis
colnames(afd_portfolio2) # check the columns at the end to derive the relevant column names
afd_mangroves<-tidyr::unnest(afd_portfolio2,
                     cols="mangroves_area")

# view unnested data (only relevant columns are selected for the view and geometry is dropped)
colnames(afd_mangroves)  # check the columns at the end to derive the relevant column names
afd_mangroves %>%
  sf::st_drop_geometry() %>%
  dplyr::select(ID_pr,WDPAID,year,mangrove_extent) %>% 
  View()


**However, when I run "colnames(afd_mangroves) ", I get :** 

> colnames(afd_mangroves) 
 [1] "WDPAID"     "WDPA_"      "PA_DE"      "NAME"       "ORIG_"      "DESIG"      "DESIG_E"    "DESIG_T"    "IUCN_"      "INT_C"     
[11] "MARIN"      "REP_M"      "GIS_M"      "REP_A"      "GIS_A"      "NO_TA"      "NO_TK"      "STATUS"     "STATUS_"    "GOV_T"     
[21] "OWN_T"      "MANG_A"     "MANG_P"     "VERIF"      "METAD"      "SUB_L"      "PAREN"      "ISO3"       "SUPP_"      "CONS_"     
[31] "ID_pr"      "Nm_d_"      "N____"      "ID_cn"      "Lblldc"     "Dsc__"      "Mntnt"      "Mtglb"      "E____"      "mnt__"     
[41] "Prodt"      "Lbllp"      "Dvsn_"      "Lblldv"     "Agenc"      "Lbllg"      "Ann_c"      "Dt_ct"      "D__1_"      "D______"   
[51] "D____C"     "DurdcncrsA" "DrdcncrsAn" "IdPys"      "Pays"       "Drct_"      "Atrsp"      "Ett__"      "Lbllt"      "Bnfcr"     
[61] "Rspns"      "Dr____"     "Dt_____"    "Cfn_1"      "Cfn_2"      "Cfn_3"      "Cfn_4"      "Cfn_5"      "Cfn_6"      "KFW"       
[71] "mtrs_"      "Sprfc"      "n_AP_"      "détal"      "projt"      "cmmnt"      "WDPAID_2"   "WDPAID_3"   "Nm_AP"      "Cmmnt_1"   
[81] "assetid"    "value"      "geometry"  


WHERE you can see there is no "year" column, nor "mangrove_extent" column, so I'm getting an error message " Can't subset columns that don't exist". 

Why don't the year and mangrove_extent appear ?

Thank you so much

**Comment by goergen95** [comment]
Moving to #107 because this is unrelated to the original issue.
