### ISSUE TITLE
SSL certification error for downloading SRTM Data

### ISSUE THREAD

**Issue by Shirobakaidou** [mapme-initiative/mapme.biodiversity#115]
I was trying to calculate elevation indicators, but the url for downloading the srtm data seems to be invalid.

The error message is called
`<simpleError in curl::curl_fetch_memory(url, handle = handle): Peer certificate cannot be authenticated with given CA certificates: [srtm.csi.cgiar.org] server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none>`

My script is as follows:

`library(wdpar)
library(geodata)
library(sf)
library(ggplot2)
library(mapme.biodiversity)
library(tidyverse)`

### Download gadm of MDG
`gadm <- gadm(country = "Madagascar", resolution = 1, level = 0, path = paste0(getwd(),'/data')) %>%
  st_as_sf()`

### Download wdpa
`wdpa <- wdpa_fetch("Madagascar", wait = TRUE, download_dir = paste0(getwd(), '/data'))`

### Make Bounding Box
`bbox <- st_as_sf(st_as_sfc(st_bbox(wdpa)))`

### Make Hexagon Grid
`for (i in c(5)) { `
  `cellarea <- i * (1e+6)`
  `cellsize <- 2 * sqrt(cellarea / ((3 * sqrt(3) / 2))) * sqrt(3) / 2`
  `hexa <- st_make_grid(x = bbox,
                       cellsize = cellsize,
                       square = FALSE)`
  `st_write(hexa,
           paste0(getwd(), "/data/grids/hexa_", i, "km2.gpkg"),
           append= FALSE)
}`

### Load Hexagons
`hexa <- st_read(paste0(getwd(), "/data/grids/hexa_5km2.gpkg"))`

### Crop hexagons to Country
`gadm <- st_transform(gadm, crs = st_crs(hexa))`
`intersection <- unlist(st_intersects(gadm, hexa))`
`hexa <- hexa[sort(intersection),]`

### Export cropped Hexagon Grids
`write_sf(hexa, paste0(getwd(), "/data/grids/hexa_5km2_sub.gpkg"), append = FALSE)`

### Load cropped Hexagons
`aoi <- st_read(paste0(getwd(), "/data/grids/hexa_5km2_sub.gpkg"))`
`aoi <- st_transform(aoi, "EPSG:4326")`

`ncores = 12`
`sample = FALSE`
`if(sample){
  set.seed(123)
  index = sample(1:nrow(aoi), 1000, replace = FALSE)
  aoi = aoi[index, ]
}`

`aoi = init_portfolio(aoi, years = 2000:2020,
                      outdir = "./data",
                      tmpdir = "./tmp",
                      cores = ncores,
                      verbose = TRUE)`

### Download Raster Data: Elevation
`get_resources(aoi, resources = "srtmdem")`

**Comment by goergen95** [comment]
Hi, 
thanks for reporting your issues with the package. The internet source of the SRTM resource is somewhat unreliable.. I have experienced the same issue before. What has actually helped for me was to wait a few hours/days until the server is reachable again... Sorry for that, I am looking to replace it with a more reliable source but up to now I was not able to find some source that does not require user credentials..

Also thanks for providing code to reproduce the issue you encounter. If possible, try to minimalise your example code next time. The code above creates hexagons covering the complete extent of Madagascar. Downloading the resources of that a large extent is not feasible when we try to reproduce a bug. I would advise using the [reprex](https://cran.r-project.org/web/packages/reprex/index.html) package to construct minimal reproducible examples that run in acceptable time.

Cheers!

**Comment by melvinhlwong** [comment]
Hi @goergen95, I do not agree that this issue is solved and should be closed. I would like to open this issue again. I talked to Kemeng and she tried the link again during christmas and it still does not work. The link seems to be broken and if the ressource is not working we may need to take it down from the package (which I do not prefer).

Is there a way to solve this issue  some time in the future?

@Jo-Schie For the attention to follow this discussion.

**Comment by goergen95** [comment]
Agreed, the issue seems to be that the SSL certificate of the CIGAR SRTM website is expired since November, 2. I tried to contact the website's maintainer. Let's wait for an answer. I already checked other options, unfortunately it will not be trivial to exchange the data source...

**Comment by goergen95** [comment]
I have not received an answer from the maintainers yet. Please see the [documentation](https://mapme-initiative.github.io/mapme.biodiversity/reference/nasa_srtm.html) of the latest release for instructions how to disable SSL certification checks. Please make sure to understand the risks of this before using it.

**Comment by goergen95** [comment]
I just have checked the website and the SSL certificate has been renewed, so I hope there is no need for the workaround!!!  Could you please try and give feedback on how it went?

**Comment by Shirobakaidou** [comment]
It works now!! Thank you:D

**Comment by goergen95** [comment]
Great! Thanks.
