### ISSUE TITLE
Uninterpretable Output of the `calc_indicators()` function for soil properties

### ISSUE THREAD

**Issue by Shirobakaidou** [mapme-initiative/mapme.biodiversity#116]
I was trying to calculate soil indicators using the `calc_indicators()` function. The expected output should be three values (mean, median, sd) for each feature, but the eventual output was a single `NA` for all features.

My script is as follows:

`library(wdpar)
library(geodata)
library(sf)
library(ggplot2)
library(mapme.biodiversity)
library(tidyverse)`

### Download gadm of MDG
`gadm <- gadm(country = "Madagascar", resolution = 1, level = 0, path = paste0(getwd(),'/data')) %>%
  st_as_sf()`

### Download wdpa
`wdpa <- wdpa_fetch("Madagascar", wait = TRUE, download_dir = paste0(getwd(), '/data'))`

### Make Bounding Box
`bbox <- st_as_sf(st_as_sfc(st_bbox(wdpa)))`

### Make Hexagon Grid
`for (i in c(5)) { `
  `cellarea <- i * (1e+6)`
  `cellsize <- 2 * sqrt(cellarea / ((3 * sqrt(3) / 2))) * sqrt(3) / 2`
  `hexa <- st_make_grid(x = bbox,
                       cellsize = cellsize,
                       square = FALSE)`
  `st_write(hexa,
           paste0(getwd(), "/data/grids/hexa_", i, "km2.gpkg"),
           append= FALSE)
}`

### Load Hexagons
`hexa <- st_read(paste0(getwd(), "/data/grids/hexa_5km2.gpkg"))`

### Crop hexagons to Country
`gadm <- st_transform(gadm, crs = st_crs(hexa))`
`intersection <- unlist(st_intersects(gadm, hexa))`
`hexa <- hexa[sort(intersection),]`

### Export cropped Hexagon Grids
`write_sf(hexa, paste0(getwd(), "/data/grids/hexa_5km2_sub.gpkg"), append = FALSE)`

### Load cropped Hexagons
`aoi <- st_read(paste0(getwd(), "/data/grids/hexa_5km2_sub.gpkg"))`
`aoi <- st_transform(aoi, "EPSG:4326")`

`ncores = 12`
`sample = FALSE`
`if(sample){
  set.seed(123)
  index = sample(1:nrow(aoi), 1000, replace = FALSE)
  aoi = aoi[index, ]
}`

`aoi = init_portfolio(aoi, years = 2000:2020,
                      outdir = "./data",
                      tmpdir = "./tmp",
                      cores = ncores,
                      verbose = TRUE)`

### Download Raster Data: Soilgrid
`get_resources(aoi, resources = c("soilgrids"), 
              layers = c("clay", "nitrogen", "phh2o", "soc"),
              depths = c("0-5cm", "5-15cm", "30-60cm"),
              stats = c("mean"))`

### Calculate Indicators
`grid_soil <- calc_indicators(x = aoi, 
                             indicators = "soilproperties",
                             stats_soil = c("mean", "median", "sd"),
                             engine = "extract")`
`grid_soil_unnested <- grid_soil %>% unnest(soilproperties)`
`print(unique(grid_soil_unnested$value))`

**Comment by goergen95** [comment]
Thanks, can confirm this bug. It was caused by an incorrect return class of the internal functions. I am trying to merge the changes into main today.

**Comment by goergen95** [comment]
Could you give it a try with recent development version via:
```r
remotes::install_github("mapme-initiative/mapme.biodiversity")
```

**Comment by Shirobakaidou** [comment]
> Could you give it a try with recent development version via:
> 
> ```r
> remotes::install_github("mapme-initiative/mapme.biodiversity")
> ```

After removing the old version and installing the newest version, another error message occurred when I was trying to run `get_resources(aoi, resources = c("soilgrids"), layers = c("clay", "nitrogen", "phh2o", "soc"), depths = c("0-5cm", "5-15cm", "30-60cm"), stats = c("mean"))`

The error message is called

`<error/vctrs_error_scalar_type>`
`Error in stop_vctrs():`
`! Input must be a vector, not an environment.`

`Backtrace:`
  `1. mapme.biodiversity::get_resources(...)`
 `16. vctrs:::stop_scalar_type(<fn>(<env>), "")`
 `17. vctrs:::stop_vctrs(msg, "vctrs_error_scalar_type", actual = x)`
`<simpleWarning: Download for resource soilgrids failed. Returning unmodified portfolio object.>`
