### ISSUE TITLE
add example ressources for all supported resources 

### ISSUE THREAD

**Issue by goergen95** [mapme-initiative/mapme.biodiversity#12]
We should include example resources in inst/res clipped on the sierra_de_neiba_478140.gpkg polygon. The raster files should be highly compressed (LZW and PREDICTORS=2) in order to reduce file size. Could you please handle this for the resources you implemented?

**Comment by Ohm-Np** [comment]
I added example resources for these indicators:

`ecoregions` `esalandcover` `nasagrace (drought)` `srtmdem` `traveltime` `worldpop` `mintemperature` `maxtemerature` `precipitation`

However, there is no `mangrove` extent in the region of interest: _sierra_de_neiba_478140.gpkg_ polygon.

**Comment by goergen95** [comment]
Great, thanks! It would be nice if you could include another extent for mangrove. Also, we need to reconsider the naming convention of the files written to disk for esalandcover because due to the length of the filenames warnings are issued by R CMD check. I would propose the following:

```
org = "W100N60_PROBAV_LC100_global_v3.0.1_2018-conso_Discrete-Classification-map_EPSG-4326.tif"
new = "W100N50_LC100_v3.0.1_2018.tif"
```
Could you please try to implement this in the `.get_esalandcover()` function?
