### ISSUE TITLE
Include tests for indicator functions

### ISSUE THREAD

**Issue by goergen95** [mapme-initiative/mapme.biodiversity#13]
Once #12 has been implemented please write tests for the indicator functions corresponding to the resources. Please consider this [file](https://github.com/mapme-initiative/mapme.biodiversity/blob/main/tests/testthat/test-calc_precpitation.R) as an example how test for indicators should be implemented

**Comment by Ohm-Np** [comment]
_track progress - tests_

- [ ] srtmdem
- [ ] tri
- [ ] accessibility
- [ ] drought
- [ ] worldpop
- [ ] climate (worldclim)
- [ ] esalandcover
- [ ] ecoregions
- [ ] mangrove
