### ISSUE TITLE
Numerical results for drought_indicator/landcover changed in GA tests

### ISSUE THREAD

**Issue by goergen95** [mapme-initiative/mapme.biodiversity#134]
For currently unknown reasons the numerical results for the drought_indicator and landcover results changed on GA across all versions of R and OSs. I was able to reproduce this with a local machine. Still not sure what is causing this... Checked versus different versions of sf and terra, no clear result here since the error also occurs with older versions..

**Comment by goergen95** [comment]
On CRAN servers this has not come up..., yet.

**Comment by goergen95** [comment]
I assume that changes introduced in terra v1.7-3 lead to different numerical results in using `extract()` and `zonal()`. This does not come up at CRAN because snapshot tests are skipped by default for instability reasons. My suggestion would be to update the snapshots with the most recent version of terra so that GA checks run successfully. This is somehow related to #72 and #69. We should put some effort into documenting the zonal engines and also make sure that all engines return identical results (e.g. by taking the coverage of cell into account), if possible.

**Comment by fBedecarrats** [comment]
And check + document possible differences with other tools, such as GRASS (but isn't GRASS doing the work with terra), raster package or GEE? Or do you think that the differences are negligible?

**Comment by Jo-Schie** [comment]
![image](https://user-images.githubusercontent.com/25028884/224481925-c5e4271c-77ef-4e8c-8424-5cd0cb444291.png)

If I'm not totally mistaken then we discussed this already several times. Terra routines and exactetract Work differently. The latter crops the rasters thus leading to more accurate results (therefore exactextract). This is especially relevant for small areas or low raster resolutions. Exactextract is also more efficient in many cases thus the preferred method from my point of view. Comparing both is not really sense-full to me.

**Comment by goergen95** [comment]
This thread here is not so much about discussing the differences but the fact that GA checks are failing for unknown reasons. This head checked out fine locally but fails on GA. Currently at a loss here becaus IDK what is causing this

**Comment by Jo-Schie** [comment]
Sure. I was only referring to not compare the results of different engines amongst each other in testing because by nature they will never yield the same results. Not sure about the two terra methods but at least for exact extract that'll be the case...

**Comment by goergen95** [comment]
As seen by the results of the latest GA runs, the snapshots cause more trouble than being helpful. We would have to think about what we want the tests to actually indicate to us. Current fails are introduced by changes to the formatting of tibble outputs. I don't think that this is something we care too much about. I currently see the following points as important for testing indicators:

- check that the column names are as expected and changes are catched early
- numerically identical results on all OSs and versions of R
- catch differences in the numerical results due to changes in upstream packages

This would require some re-works of the testing infrastructure. I think it is necessary and has a very high priority because it hinders further development of the package. Has anyone further ideas about what changes we want to catch with testing indicators?

**Comment by goergen95** [comment]
**Background**
Snapshot tests are fragile and applied to tibbles they might cover actual regressions introduces by changes in upstream packages. We thus need to refactor the test suite to be less depended on snapshot tests and actually deliver clear insights
on changes introduced to the code base by us or for differences in numerical results by changes in upstream packages.

Definition of done
New test suite that is less dependent on snapshots tests and that passes GA CI as well as CRAN test checks.

Complexity
Medium. Lot of test files have to be altered to make the CI pass. Additionally, for at least two indicators there are changes in the numerical results for currently unknown reasons.

**Comment by goergen95** [comment]
@melvinhlwong and @Jo-Schie this was fixed yesterday. GA checks check out fine now. That means we are set up to continue on other issues (I will finalize the parallelization issue next week). Happy Easter! :)

**Comment by Jo-Schie** [comment]
Sounds great @goergen95 . Happy Easter to you as well!
