### ISSUE TITLE
Differences between "engine" types

### ISSUE THREAD

**Issue by Shirobakaidou** [mapme-initiative/mapme.biodiversity#140]
Hello Darius, 

What is the difference between the `engine` type `zonal`, `extract` and `exactextract` in the `calc_indicator()` function?

**Comment by goergen95** [comment]
Hi! As indicated in the [terminology](https://mapme-initiative.github.io/mapme.biodiversity/articles/terminology.html) vignette, these engines are based on different functions to obtain zonal statistics from vector-raster operations. Note, that these engines might yield to different numerical results. Please check the links mentioned in the vignette to get mor information how these functions work.
