### ISSUE TITLE
Apply tidyverse code style to whole package

### ISSUE THREAD

**Issue by karpfen** [mapme-initiative/mapme.biodiversity#153]
Following the discussion regarding code style in https://github.com/mapme-initiative/mapme.biodiversity/pull/151 I noticed that quite a lot of the code deviates from the tidyverse style.
I think it's a simple fix though, so I'm gonna do a PR on it later. But if you have any questions or concerns, please let me know.

**Comment by Jo-Schie** [comment]
Sounds great to me and we can really appreciate contributions on refactoring!

**Comment by goergen95** [comment]
Sure, please go ahead. Once you are done, we can also consider encouraging the usage of our [pre-commit hooks](https://github.com/mapme-initiative/mapme.biodiversity/blob/main/.pre-commit-config.yaml) as well as the [styler](https://github.com/mapme-initiative/mapme.biodiversity/blob/main/.github/workflows/pr-commands.yaml) pull-request commands (I just tested the last one  in this [dummy PR](https://github.com/mapme-initiative/mapme.biodiversity/pull/154)).

**Comment by karpfen** [comment]
New PR in here: https://github.com/mapme-initiative/mapme.biodiversity/pull/156

**Comment by goergen95** [comment]
Thanks. Now merged in main. We could additionally fix the issues raised by [lintr::lint_package()](https://lintr.r-lib.org/reference/lint.html). Then, pre-commit hooks could be enabled by all active developers to get only "clean" commits?

**Comment by karpfen** [comment]
Cool, thanks!
Oh, I assumed `lint_package()` would be redundant with the coding style. I think it's definitely a good idea to enforce this through hooks.
I can look into it and see if I can get it working.

**Comment by goergen95** [comment]
hi @karpfen closing for now. Feel free to open a PR/issue if you find time to look into the outcome of lintr.
