### ISSUE TITLE
Carbon Storage in Protected Areas

### ISSUE THREAD

**Issue by Jo-Schie** [mapme-initiative/mapme.biodiversity#160]
**Definition of reasearch question:**

How much carbon is stored in the total biomass in protected areas. 

Total carbon can be conceptualized as a sum of aboveground, belowground and soilcarbon. See also the DOPA Factsheets [here](https://dopa.jrc.ec.europa.eu/var/www/app/app/static/dopa/files/factsheets/en/DOPA%20Factsheet%20J1%20EN%20Soil%20Carbon.pdf), [here ](https://dopa.jrc.ec.europa.eu/var/www/app/app/static/dopa/files/factsheets/en/DOPA%20Factsheet%20J2%20EN%20Above-Ground%20Carbon%20Stock.pdf) and [here](https://dopa.jrc.ec.europa.eu/var/www/app/app/static/dopa/files/factsheets/en/DOPA%20Factsheet%20J3%20EN%20Below%20Ground%20Carbon.pdf). 

**Purposes:**

* Assist Targeting of areas (e.g. prioritize areas with high carbon storage or irrecoverable carbon).
* Assist Reporting on current portfolio ("helps to protect xyz amount of carbon).  
* Assist Monitoring (if data is cross-sectional)
* Assist Evaluation (above-ground carbon could be used as a matching variable since it can be a a proxy for timber availability which is a driver for selective logging which is often the initial stage of forest degradation and subsequent deforestation). 

**Definition of indicator**

Sum of carbon (metric tons) stored in living and dead biomass within an AOI. 

**Possible data-sources**
See above the DOPA sources. Not sure if there is already time-series available. ESA will have some sophisticated data starting around 2024/2025 see [here](https://www.esa.int/Applications/Observing_the_Earth/FutureEO/Biomass). Besides a refreshed review on literature would be necessary because I think the DOPA stuff is outdated. 

Side-Note: There are also authors arguing to focus on irreceveroable carbon, which is  carbon that if once released to the atmosphere cannot be reabsorbed e.g. by vegetation recovery.... see [here](https://www.nature.com/articles/s41893-021-00803-6). I think it is a valid point but would be only come after having plausible numbers on "normal" carbon. 

**spatial and temporal resolutions available**
tbd

**other available R packages or routines that could help for code development**
tbd

**Comment by vuillota** [comment]
I had a look to [this recent article](https://www.nature.com/articles/s41467-023-38073-9) where authors estimate the amount of above-ground carbon stored in PAs, and compare it to the storage in non-PAs. 
They use the publicly available data from NASA, and have a 1km spatial resolution for above-ground carbon density. The area covers +/- 52° latitude. The data are collected since 2018, and authors generate a map for the year 2020 in their article. 
Maybe this can be an interesting source of data, for above-ground carbon at least !

**Comment by Jo-Schie** [comment]
Cool. Thanks for the advice @vuillota 😃

**Comment by Jo-Schie** [comment]
Thanks for the hint @vuillota 😃

**Comment by goergen95** [comment]
Thanks for the suggestion. Please note that the authors use data from the [GEDI](https://daac.ornl.gov/GEDI/guides/GEDI_L4A_AGB_Density.html) mission. To my understanding, because the sensor is mounted to the ISS, data is only available for about 70% of pixels of  between +/- 50° latitude. As such, I don't think it is suitable to be included in the package. However, there might be interesting derived products (see e.g. [here](https://arxiv.org/abs/2304.07213) a study by Meta folks to derive canopy height models using GEDI data to construct a reference data set).

**Comment by goergen95** [comment]
I took a look at the resources you linked @Jo-Schie.
DOPA processes all three types of carbon storage on the protected area, eco-region, and national level.

- For Above-Ground-Carbon (AGC) estimation they use [globbiomass.org](https://globbiomass.org/wp-content/uploads/GB_Maps/Globbiomass_global_dataset.html) data on Above-Ground-Biomass (AGB) from 2010. There is also an AGB dataset on [Global Forest Watch](https://data.globalforestwatch.org/datasets/aboveground-live-woody-biomass-density/explore) for the year 2000 with higher spatial resolution.

- Below-Ground-Carbon (BGC) is estimated by DOPA from the AGB data set mentioned above by applying root-to-shoot ratios modeled for respective eco-zones.
 
- Soil-Organic-Carbon (SOC) is estimated up to a depth of 30 cm and is based on a data set of national reportings harmonized by [FAO]( http://www.fao.org/global-soil-partnership/pillars-action/4-information-and-data-new/global-soil-organic-carbon-gsoc-map). An alternative could be the SOC layer of [soilgrids](https://www.isric.org/explore/soilgrids), which is already included in the package.

I was not successful downloading any raw data from DOPA, yet. I think that it will be very hard in the foreseeable future to find ready-to-use data sets on these three indicators with a yearly cadence. We could think about replicating DOPA analysis with the data layers we already have in the package.

**Comment by karpfen** [comment]
@goergen95 you can access the DOPA raw data on the WDPA region level like this:
```
url <- "https://dopa-services.jrc.ec.europa.eu/services/d6dopa40/protected_sites/get_wdpa_all_inds?format=csv&wdpaid=666"
dat <- read.csv(text = readLines(url, warn = FALSE), sep = "|")
```

This only gives a single result per WDPA region and no time series, so I guess this is of limited use.

**Comment by goergen95** [comment]
I just had another look at the [Noon et al.](https://www.nature.com/articles/s41893-021-00803-6#Sec7) paper's methodology and my understanding is that the category 'manageable carbon' is the total sum of carbon:

> (2) Create a ‘total manageable carbon’ map for terrestrial and coastal ecosystems. This includes aboveground biomass carbon (AGC), belowground biomass carbon (BGC) and soil organic carbon (SOC) stocks.

These layers, together with the vulnerable and irrecoverable data layers are available for download [here](https://zenodo.org/record/4091029), even-though only differentiating between biomass and soil carbon (so we could not differentiate between AGC and BGC).

**Comment by goergen95** [comment]
Carbon layers of Noon et al. implemented in [mapme.indicators](https://github.com/mapme-initiative/mapme.indicators).
