### ISSUE TITLE
 A beginner's contribution to enhance understanding 

### ISSUE THREAD

**Issue by lenaigmoign** [mapme-initiative/mapme.biodiversity#169]
About the output-wide vignette :
"In this case, the result has 9 rows just like the original data frame.
We can now export our portfolio for example as a geopackage that can be read directly into e.g. QGIS or as a CSV without the geospatial information" 

It could be interesting to add a sentence between the two lines to emphasize the connection with the wide format, for example : 
"In this particular scenario, where the only variable is elevation_mean, the object port_wide_1 contains just one value per polygon. 
This aligns well with the characteristics of the wide format, which can be easily understood and processed by various (geospatial) software."

I tried the tutorial following @fBedecarrats suggestion, and I have nothing to criticize. It's really well-explained and didactic.

**Comment by fBedecarrats** [comment]
Thank you for the feedback @lenaigmoign. @goergen95 , @Jo-Schie , as she is starting to use the package and does not have a lot of experience with R (but learns VERY fast), @lenaigmoign seems the perfect target for the documentation. She was puzzled by the long/wide outputs so I recommended that she reads the new vignette, and asked her for a feedback to confirm that it was clear and didactic. Thanks to her!

**Comment by goergen95** [comment]
Thank you very much for your feedback on the new vignette! Glad to hear that it does a good job at explaining wide vs. long format. 

I would be very happy to include your suggested changes. Please provide them as a Pull-Request because that is the usual way how we would expect feedback concerning the documentation.

**Comment by goergen95** [comment]
Thanks a lot @lenaigmoign. I included your suggestions in the latest version.
