### ISSUE TITLE
Feedback: User Documentation

### ISSUE THREAD

**Issue by goergen95** [mapme-initiative/mapme.biodiversity#18]
Hi @Jo-Schie and @Ohm-Np,
I updated the package to include some user-facing documentation. It would be great if you could read through it and we can collect any potential feedback here in this issue. You can follow this [link](https://mapme-initiative.github.io/mapme.biodiversity/articles/introduction.html) to get to the online version and click through the pages in the articles section of the navbar.

**Comment by Jo-Schie** [comment]
Hi @goergen95 can you copy quickly the link to the Ressource so i can edit it directly

**Comment by goergen95** [comment]
Sorry, what resource do you mean?

**Comment by Jo-Schie** [comment]
this is in main correct? So i`d have to push changes to the `introduction` to main?

**Comment by Jo-Schie** [comment]
Here is one suggestion that we noted just yesterday when going through the documentation: We were unable to find an overview of all resources and indicators. That should be prominently linked. Maybe it could be even a single page in the vignette or something.

**Comment by goergen95** [comment]
please find an updated version of the userguide (now referred to as "quickstart") online. I would suggest that we include an overview of all supported resources and indicators in the README. That yet has to be properly desgined anyway.. From there we could directly link to the quickstart vignette. What do you think?

**Comment by melvinhlwong** [comment]
I will write down my comments in this issue here

Readme file

- [ ] "This package is platform agnostic and provides the possibility to e.g. analyze the World Database of Protected Areas (WDPA)." It appears to be two sentences. Also, what does agnostic mean? Add short sentence?

**Comment by goergen95** [comment]
@melvinhlwong please see my edits in your comment above.
