### ISSUE TITLE
Progress track - indicator calculation functions

### ISSUE THREAD

**Issue by Ohm-Np** [mapme-initiative/mapme.biodiversity#19]
_create new functions for these indicators_
- [x] climate (worldclim)
- [x] worldpop
- [x] esalandcover
- [x] ecoregions
- [x] mangrove

_improve_

- [x] `.get_esalandcover()` 
_see comment #12_

**Comment by goergen95** [comment]
Hi! Please see the first draft of the [contributing guideline](https://mapme-initiative.github.io/mapme.biodiversity/articles/contributing.html). I would be glad to receive your feedback on the content and readability over at #29. Maybe its of help while you implement the indicators mentioned above.

**Comment by Ohm-Np** [comment]
@goergen95, for mangrove data which extends from 1996 to 2016, should we expect multiple polygons (as overlay) as arguments to be passed to the calculation functions?

**Comment by goergen95** [comment]
hi @Ohm-Np please see [7f0e763](https://github.com/mapme-initiative/mapme.biodiversity/pull/8/commits/7f0e763d2787d8f9011fab4d6e50fcd83e9e4e83). You can expect the resource to be a list cropped to the extent of an asset. The names of the list will default to the basename of the respective file. Let' me know if you require a different handling.

**Comment by goergen95** [comment]
Guess in introduced that myself. Using sf takes quite a while... Nevermind, I will change it back by tomorrow morning
