### ISSUE TITLE
The vignette output-wide referes to Worldpop when the example is with Nelson et al.

### ISSUE THREAD

**Issue by fBedecarrats** [mapme-initiative/mapme.biodiversity#195]
The text in the vignet writes:

> As a simple example, suppose we interested in extracting the sum of population counts in our portfolio. As usual, we will have to make available the WorldPop resource as well as requesting the calculation of the respective indicator.

But the subsequent example is with Nelson resource.

**Comment by goergen95** [comment]
Thanks!
