### ISSUE TITLE
Wrong link in parallel computing warning message

### ISSUE THREAD

**Issue by karpfen** [mapme-initiative/mapme.biodiversity#197]
The link in this warning message is outdated: https://github.com/mapme-initiative/mapme.biodiversity/blob/6f056e2dcb4fda829cffb20951d0a0d6cd689d2e/R/portfolio.R#L91

It should be replaced with https://github.com/mapme-initiative/mapme.biodiversity/#a-note-on-parallel-computing

**Comment by goergen95** [comment]
Thanks! Well spotted. Would you prefer the link to refer to the README on GitHub or to the pkgdown website?
