### ISSUE TITLE
Input/Output structure for indicators

### ISSUE THREAD

**Issue by goergen95** [mapme-initiative/mapme.biodiversity#2]
Below we need a list with the inputs (e.g. all required resources) for each supported indicator. This overview will be the base for the package internal backlog function indicating supported indicators. We need a list of the names of the resources as well as their format and any additional arguments, when possible with their allowed values. As an example consider the indicator tree cover, here simply called "treecover" as it will be backlogged in the internal function:

```r
indicators = list(
  "treecover" = list(
    "resources" = list(
       "umd_tree_cover_density_2000" = "raster",
       "umd_tree_cover_lossyear" = "raster"
     ),
     "arguments" = list(
       "timeframe" = c(2000:2020),
       "minDensity" = c(10,15,25,50,75,100),
       "minSize" = c(0:Inf)
       )
   )
)
   
```

For now, a tabular overview would suffice.

**Comment by Ohm-Np** [comment]
**I/O indicators in tabular form**:-

|indicators|resources|format|argument|values|Remarks|
|-|-|-|-|-|-|
|net forest carbon flux|gfw_forest_carbon_net_flux|raster|grid|"00N_040W"|optional: provide index polygon as argument|
|ecoregions|terrestrial_ecoregions_world|vector|-|-|polygon is global, need to load the whole polygon|
|mangrove extent|gmw-v2-1996|vector|timeframe|c(1996, 2007:2010, 2015, 2016)|
|copernicus land cover|global_land_cover_2015|raster|timeframe|c(2015:2019)|
||||grid|"W060S40"|optional: provide index polygon as argument|
|minimum temperature|wc2.1_2.5m_tmin_2000-01|raster|timeframe (yyyy)|c(2000:2018)|
||||timeframe (mm)|c(01:12)|as strings|
|maximum temperature|wc2.1_2.5m_tmax_2000-01|raster|timeframe (yyyy)|c(2000:2018)|
||||timeframe (mm)|c(01:12)|as strings|
|precipitation|wc2.1_2.5m_prec_2000-01|raster|timeframe (yyyy)|c(2000:2018)|
||||timeframe (mm)|c(01:12)|as strings|
|population count|global_mosaic2000|raster|timeframe|c(2000:2020)||
|accessibility to cities|acc_5k_10k|raster|range|"5k_10k"||
||||index|14189840|respective range and index information is in download function|
|clay content in the soil|clay_content_0_cm|raster|depth|c(0,10,30)|depth in cm|
|drought indicator|gws_perc_025deg_GL_20030203|raster|timeframe (yyyymmdd)|c(20030203:20220131)|weekly updates till present|
|terrain ruggedness index|tri_6675|raster|zoom_level|c(0:15)|use package `elevatr`|for our project optimum zoom level is 12|

**Comment by Jo-Schie** [comment]
HI @goergen95 AND @Ohm-Np . 
As promised a little priority list of the variables to start with: 

- forest area, emission from forest loss
- TRI and elevation
- accessibility to cities (please make sure to support all different city sizes)
- clay content in the soil  
- drought indicator
- (precipitation)

As for precipitation. Is there any dataset that goes beyond 2018? our observation period is 2000 until 2020. If we get data only until 2018 all observations after 2018 are dropped from the further analysis.

Also, I wanted to discuss if we could add support for the hurricane data that I process [here](https://github.com/openkfw/mapme.protectedareas/blob/main/code/development/hurricanes.R). I'm not sure if it makes sense to include the data processing routines into the package. 

Maybe you @goergen95 can make a suggestion whether this makes conceptually sense or not. I'm not sure if there are any heavy pre-processing routines for other variables... I guess not. One Idea could be to add only support for the analysis, then store the data somewhere where it is permanently accessible (harvard dataverse or something) and leave the preprocessing routine in the mapme.protectedareas repo, so people could look it up in case they want to update it... We could add a link to this repo in the tutorial here...not sure what the best solution is.

**Comment by goergen95** [comment]
hi @Jo-Schie, 
thanks for your comment and the prioritization of indicators!

Concerning your question on precipitation, we could use CHIRPS. Under this [link](https://data.chc.ucsb.edu/products/CHIRPS-2.0/global_monthly/) you will find the global data layers with monthly resolution. It was news to me that the product is now also distributed as COGs, but I think that is great news! As of today the latest consolidated data layer is from 09.2021. I think that also preliminary layers are distributed, however, these are likely to include changes when they undergo the consolidation process. 

Concerning the hurricane indicator, I will have to take a deeper look into your script. But from my first intuition why not include it as a resource to download and then an indicator to calculate? If it is an indicator that can be calculated on a asset level, e.g. a single protected area polygon, I do not really see a problem. There are some indicators, e.g. forest loss/co2 emissions, that demand unlikely more computational resources than others, e.g. accessibility,  but users still are able to decide whether or not to calculate that indicator for their analysis.

**Comment by Jo-Schie** [comment]
Hi Darius. OK that sounds great then please go for the suggested data set with monthly resolution.

**Comment by goergen95** [comment]
For your reference, with  [ed0d02b](https://github.com/mapme-initiative/mapme.biodiversity/commit/ed0d02bee6b8eaefe5634cf943b1cc55d21cafbe) support for the CHIRPS resource was added
