### ISSUE TITLE
Top ribon on mapme-initiative.github.io is not legible 

### ISSUE THREAD

**Issue by fBedecarrats** [mapme-initiative/mapme.biodiversity#222]
Hi! It seems that some change as made on the police color for the https://mapme-initiative.github.io/mapme.biodiversity/index.html webpage, and now the text is of the same color than the background:
![image](https://github.com/mapme-initiative/mapme.biodiversity/assets/3328347/e1d264a3-8c73-47db-ac45-90fee7f6aa00)

The text is still there, but we can only see it when it is highlighted (when selecting it):
![image](https://github.com/mapme-initiative/mapme.biodiversity/assets/3328347/d4fc1ea0-95dd-4275-90b5-29b1274adcfe)

**Comment by goergen95** [comment]
Hi! Thanks for spotting this. Really weird, `.pkgdown.yaml` has not been touched in a while. I'll open a PR...

**Comment by fBedecarrats** [comment]
I think that it is cute, but that the contrast is not high enough for color-blind people. I think that the Web Content Accessibility Guidelines sets specific color constrast metrics to make sure that all users can access it properly.
