### ISSUE TITLE
Mapme website's menu bar disappeared

### ISSUE THREAD

**Issue by melvinhlwong** [mapme-initiative/mapme.biodiversity#226]
Hi @goergen95 ,

I have attached a screenshot of the mapme page. The navigation bar has disappeared. In fact, the links are still there but the buttons have the same color as the decorative bar. Could you please fix this?
Thanks a lot!
![image](https://github.com/mapme-initiative/mapme.biodiversity/assets/33483784/1e1c76b9-d08f-4da9-896c-b331fd4697ba)

**Comment by goergen95** [comment]
See #222, merging associated PR now. We can always optimize the color scheme later.
