### ISSUE TITLE
Add GSW indicators

### ISSUE THREAD

**Issue by karpfen** [mapme-initiative/mapme.biodiversity#234]
The global surface water data are available via their website. The aim is to include a selection of them in the package, namely

- GSW Occurrence
- GSW Reccurence
- GSW Transition Classes
- GSW Change
- GSW Seasonality

DoD:
- [x] Include indicators
- [x] Add unit tests

Update 2024-02-19

- [ ] Adjust indicators so it is possible to get an estimate of the surface water area given rather than the ratio of water-pixels over time.

**Comment by karpfen** [comment]
GSW indicators are finished and included in the mapme package now (see https://github.com/mapme-initiative/mapme.biodiversity/pull/235).

**Comment by karpfen** [comment]
- [ ] Update README to show new Indicators + Resources

**Comment by goergen95** [comment]
Just realised that the resources are called `global_surface_water_*` whereas the indicators are called `gsw_*.` Would you mind applying the abbreviation? If we do it simply, we would have resources and indicators with the same name (which is not a problem from the technical standpoint, I guess) but maybe we also could think of a smarter way to name things :laughing: Its not just the GSW resource, but applies to others as well... You have any ideas?

**Comment by goergen95** [comment]
Well, yeah, if we think of #232 it might actually be a problem in the future...

**Comment by karpfen** [comment]
I think I'll open a new issue for renaming things, because I feel that will be a bigger one and I have some ideas already.

**Comment by goergen95** [comment]
@karpfen, the GSW resources currently lack proper documentation. Could you please provide them?

**Comment by karpfen** [comment]
@goergen95 sorry, I must have missed your comment, just saw it.
I documented the individual indicators in their respective .calc* functions (e.g. https://github.com/mapme-initiative/mapme.biodiversity/blob/main/R/calc_gsw_occurrence.R#L3), is that what you mean?

**Comment by goergen95** [comment]
Yep, but they do not show up for users, e.g. [here](https://mapme-initiative.github.io/mapme.biodiversity/reference/index.html). Please refer to other resources/indicators how to document them properly. There is also a section on that in the developers guide.
