### ISSUE TITLE
Ideas for new indicators

### ISSUE THREAD

**Issue by Jo-Schie** [mapme-initiative/mapme.biodiversity#25]
@melvinhlwong @goergen95 @Ohm-Np 

This is a list of indicators that we should discuss next week whether @goergen95 could still work on them in this month (or at a later stage). Feel free to complement the list also from your side. 

- [x] Fire occurence
- [x] Fire burned areas
- [x] Nightlights (monthly VIIRS)
- [x] land cover in forest loss areas (combination of ESA and GFW)
- [x] NDVI
- [x] conflict (ACLED & UCDP GED): E.g. occurences and number of deaths by violence type -> precision codes are important -> ask @melvinhlwong 
- [ ] built-up areas e.g. distance to built-up areas

**Comment by melvinhlwong** [comment]
- [ ] Average temperature (monthly)
- [ ] Not sure to which extent this is possible: hours of sunlight or photovoltaic potential

**Comment by Jo-Schie** [comment]
- [ ] irrecoverable carbon
- [ ] rooting depth of trees
- [ ] GDP Gridded
- [ ] Built up areas or proximity to built up areas
- [ ] Biomass (above ground, below ground + soil organic carbon) -> already exist in JRC for WDPA
- [ ] Inland surface water -> already exists from JRC for WDPA
- [ ] Forest Fragmentation (just as in the old forest package)
- [ ] Fire alerts or forest cover loss alerts (see GFW homepage)

**Comment by Jo-Schie** [comment]
- [ ] Agricultural Price Index data. -> this would be a very relevant covariate for the IE but I guess this data is, if at all, only available on country level.

**Comment by melvinhlwong** [comment]
@Jo-Schie 
I would not recommend gridded GDP. It's coarse in time and space. Method-wise it has too many caveats for the stuff we do. 

Also, what is irrevocable carbon? It sounds like this dataset is rather static in time. If so, we need to think about the value added for us.

**Comment by Jo-Schie** [comment]
Prioritized list:

1. Fires (occurence and burned areas)
2. NDVI (e.g. MOD13Q1: 16-day 250m VI, ?-present)
3. Land-cover in loss areas (ESA 2015-today, ESRI ?)
4. Inland surface water (JRC/Global surface water, 1984 -present)
5. VIIRS monthly (VIIRS Day/Night Band (Nighttime Lights, 1982-present))
6. conflict (UCDP GED, 1989-present,point data)
7. temperature (monthly averages)
8. conflict (ACLED, 2000-present, point data)

**To be evaluated**

- [ ] data-source
- [ ] temporal and spatial resolution
- [ ] already code existing? (e.g. from @Ohm-Np)
- [ ] complexity of implementation (working days)

**Comment by Jo-Schie** [comment]
@goergen95 : could you look up the two lower points in my last comment so that we can have a rough estimation tomorrow in our meeting about the scope of different additional indicators to be implement within a new assignment...

**Comment by melvinhlwong** [comment]
@Jo-Schie I think I would like to add carbon dioxide or carbon monoxide to the list of very important variables. I can explain tomorrow.
