### ISSUE TITLE
Request: make checking internet connectivity optional

### ISSUE THREAD

**Issue by karpfen** [mapme-initiative/mapme.biodiversity#262]
`get_resources()` currently checks for internet connectivity when it's called (see https://github.com/mapme-initiative/mapme.biodiversity/blob/c7d9bd702e2ec2147fd99efa5715af05a32edb3d/R/get_resources.R#L17).

I think this is a good idea in general, but right now I'm having issues because of a firewall blocking google.com for me.

@goergen95 Do you think it would be a good idea to implement an override for this?
Maybe there could be a parameter in `mapme_options` to either provide an alternative URL or just `NULL` to disable checking at all.

**Comment by goergen95** [comment]
Good idea! How about implementing `.has_internet()` this way:

```r
.has_internet <- function() {
  if(Sys.getenv("mapme_has_internet", unset = FALSE)) return(TRUE)
  has_internet <- !httr::http_error("www.google.com")
  if (!has_internet) {
    message("There seems to be no internet connection. Cannot download resources.")
  }
  has_internet
}
```

In case `mapme_has_internet` is unset, it will trigger the request towards `www.google.com`. In case the variable is set to `TRUE` the return will be triggered early. Any other value that cannot be interpreted as a logical would throw an error.

**Comment by karpfen** [comment]
Yes, I think this is a good way to go. I'd change the naming, though to something like "check_internet_connectivity", because the package might still *use* the internet, just not checking it beforehand

**Comment by goergen95** [comment]
Ok, how about this one: this would *not* check the connection only if the variable is set to `"NO"`.

```r
if(Sys.getenv("mapme_check_connection", unset = "YES") == "NO") return(TRUE)
```
