### ISSUE TITLE
GMW 2018 data

### ISSUE THREAD

**Issue by karpfen** [mapme-initiative/mapme.biodiversity#276]
In the Global Mangrove Watch resource function, 2018 is [excluded ](https://github.com/mapme-initiative/mapme.biodiversity/blob/cac45c522d3015b131c615af6512eb23ca9b2555/R/get_gmw.R#L24) as a valid year.

However, there is also some code included, specifically to deal with the 2018 data. I was trying to fix this manually by using a custom resource function:

```r
get_gmw2 <- function(years) {
  avail_years <- c(1996, 2007:2010, 2015:2020)
  years <- check_available_years(years, avail_years, "gmw2")

  function(x,
           name = "gmw2",
           type = "vector",
           outdir = mapme_options()[["outdir"]],
           verbose = mapme_options()[["verbose"]],
           testing = mapme_options()[["testing"]]) {
    urls <- unlist(sapply(years, function(year) mapme.biodiversity:::.get_mangrove_url(year)))
    bbox <- c(xmin = -180., ymin = -38.85822, xmax = 180., ymax = 32.36822)
    fps <- st_as_sfc(st_bbox(bbox, crs = "EPSG:4326"))
    fps <- st_as_sf(rep(fps, length(urls)))
    fps[["source"]] <- urls
    make_footprints(fps, filenames = gsub(".shp", ".gpkg", basename(urls)), what = "vector")
  }
}

register_resource(
  name = "gmw2",
  description = "Global Mangrove Watch - Vector data of mangrove extent",
  licence = "CC BY 4.0",
  source = "https://data.unep-wcmc.org/datasets/45",
  type = "vector"
)
```

This seems to work for downloading the data, but `prep_resources()` still doesn't return the 2018 data. For now, I didn't manage to dig further into the problem, maybe we can have a look together this week, @goergen95

**Comment by goergen95** [comment]
Hi @karpfen,
so I had some issues with opening the data set for 2018 with GDAL which now I am unable to reproduce... I will re-enable 2018 as a valid year and let's hope that nothing else pops up!

**Comment by karpfen** [comment]
Hi @goergen95, that's strange, your fix is exactly what I tried first yesterday, but it still doesn't seem to work for me. I just ran this snippet in with an empty data directory:

```r
library(sf)
library(mapme.biodiversity)

mapme_options(outdir = "C:/data/mapme.biodiversity/", verbose = TRUE)

x <- read_sf(
  system.file("extdata", "shell_beach_protected_area_41057_B.gpkg",
              package = "mapme.biodiversity"
  )
)

res <- get_resources(
    x,
    get_gmw(years = 2018:2019)
  )

prep_resources(res)$gmw |>
  names()
# "gmw_v3_2019_vec.gpkg"

```

Is there anything else I could be doing wrong?

**Comment by goergen95** [comment]
Ah, now I got it! I did not translate the 2018 data to geodetic coordinates which resulted in no intersections. Please find [b5b12d5](https://github.com/mapme-initiative/mapme.biodiversity/commit/b5b12d512ea6e51cfc5e3a8452728354d2609869) which should work now. I also adapted your sample code a little bit to make it run on other machines as well. Please re-open if the issue persists.

**Comment by karpfen** [comment]
Aah, that was it. Thanks @goergen95!
