### ISSUE TITLE
examples fail for some new indicators

### ISSUE THREAD

**Issue by goergen95** [mapme-initiative/mapme.biodiversity#353]
See [here](https://mapme-initiative.github.io/mapme.biodiversity/dev/reference/biodiversity_intactness_index_indicator.html)

**Comment by goergen95** [comment]
Ought to be:

```r
lbii <- [system.file](https://rdrr.io/r/base/system.file.html)("res", "biodiversity_intactness_index", "lbii.asc",
package = "mapme.biodiversity")
```

**Comment by goergen95** [comment]
Same for KBA, sorry for not catching it earlier.

**Comment by goergen95** [comment]
Also add GSW time series to that list

**Comment by karpfen** [comment]
Thanks for noting, I'll make a new branch to fix these.
One thing, though: For the kba example to work, we'd need the kba data. In the unit tests I just faked it by using the aoi twice, but I think this would be very confusing in the examples.
Any idea how else we could do a kba example?

**Comment by goergen95** [comment]
I think KBA could be resolved by writing a `kbas.gpkg` with faked data. For the the GSW time series, I do not have a good idea without cluttering the example code. Except that I noted, that the output of `pkgdown` now respects the `\dontshow` directives, so that might be the place to put the code for renaming the layers.

**Comment by karpfen** [comment]
Faking the kba data sounds good to me.
I'll try and see how well the `\dontshow` works, I remember having issues with that flag before.

**Comment by goergen95** [comment]
Done in c0721a5
