### ISSUE TITLE
Use st_sf instead of st_as_sf

### ISSUE THREAD

**Issue by goergen95** [mapme-initiative/mapme.biodiversity#369]
We seem to have used undocumented behavior of `st_as_sf()` in some of the tests that now fail since https://github.com/r-spatial/sf/issues/2429 was addressed. This can be remedied by using `st_sf()` instead. Ideally, this should ship together with #368, so that we do not block a coming `sf` release.

**Comment by fBedecarrats** [comment]
Hmm. I'm not sure to understand the issue you referred to. This means that we should use `st_sf` rather than `st_as_sf` after `st_cast`?

**Comment by fBedecarrats** [comment]
Or we should always use `st_sf` rather than `st_as_sf`  in all situations?

**Comment by goergen95** [comment]
I am referring to our [automated test suit](https://github.com/mapme-initiative/mapme.biodiversity/actions/runs/10608546794/job/29405126450) that fails since that issue was addressed upstream. The way we use `st_as_sf` there no longer works. I am making no statement as to when to use the one or the other in any other context.
