### ISSUE TITLE
handle `POLYGON FULL`

### ISSUE THREAD

**Issue by edzer** [mapme-initiative/mapme.biodiversity#377]
See https://github.com/r-spatial/sf/issues/2441#issuecomment-2400404171

**Comment by goergen95** [comment]
@edzer: Thanks for your help resolving this issue. I have a [PR](https://github.com/mapme-initiative/mapme.biodiversity/pull/378) pending which checks out fine in GA against current CRAN release and `main` of `sf`. Also tested locally against `polygon_full2` and I see all green lights. I would appreciate your guidance on scheduling releases to CRAN.

**Comment by edzer** [comment]
Fantastic! Feel free to release this on CRAN, so that upcoming sf will not break it. In case `sf` gets released earlier, I will point the CRAN team to this issue. Planning to release `sf` soon.

**Comment by goergen95** [comment]
On its way to CRAN.
