### ISSUE TITLE
Wrong paper referenced in get_iucn.R

### ISSUE THREAD

**Issue by karpfen** [mapme-initiative/mapme.biodiversity#395]
The paper listed as source for the IUCN data actually refers to the human footprint paper.
@goergen95: Do you know if there should be something else be referenced here? If not, I'd just go and delete this line.

https://github.com/mapme-initiative/mapme.biodiversity/blob/87ed5d3f0a6fb0ecd12b4df9e8491490845ef699/R/get_iucn.R#L19C7-L19C54

**Comment by goergen95** [comment]
I found this [info](https://www.iucnredlist.org/about/citationinfo) how to cite IUCN Red List properly.
