### ISSUE TITLE
Atmospheric emissions

### ISSUE THREAD

**Issue by Jo-Schie** [mapme-initiative/mapme.biodiversity#46]
- [ ] Definition of reasearch question 
- [ ] Definition of the indicator
- [ ] Possible data-sources
- [ ] spatial and temporal resolutions available
- [ ] other available R packages or routines that could help for code development

**Comment by Jo-Schie** [comment]
@melvinhlwong 
potential source:

- https://disc.gsfc.nasa.gov/datasets/OCO2_L2_Lite_FP_10r/summary?keywords=OCO-2
- https://www.iup.uni-bremen.de/carbon_ghg/data/4C_D1.5_Satellite_XCO2_OBS4MIPS_v4p2_2x2_v1.pdf
- https://airs.jpl.nasa.gov/

Overview of satellites measuring xCO2

**Comment by melvinhlwong** [comment]
Thank you @Jo-Schie. Below the specification for an additional indicator.

###  Definition of reasearch question

KfW would like to assess if the investments for renewable energy power plants substitutes energy production of fossil fuel power plants. I plan to match the locations of fossil fuel power plants with xCO2 data. This allows for a time series analysis around the time where the renewable energy started its operations.

### Definition of the indicator

 xCO2 is a column average in the atmosphere of CO2. Fossil fuel power plants emitt CO2 and xCO2 is a rough approximation of that. Studies have shown that [mapping xCO2 to power plant](https://agupubs.onlinelibrary.wiley.com/doi/full/10.1002/2017GL074702) is possible. Still, there are major limitations that have to be addressed.

###  Possible data-sources

- https://disc.gsfc.nasa.gov/datasets/OCO2_L2_Lite_FP_10r/summary?keywords=OCO-2
- https://www.iup.uni-bremen.de/carbon_ghg/data/4C_D1.5_Satellite_XCO2_OBS4MIPS_v4p2_2x2_v1.pdf
- https://airs.jpl.nasa.gov/


###  spatial and temporal resolutions available

https://disc.gsfc.nasa.gov/datasets?page=1&keywords=OCO-2
- 2014-2022 in 16 days intervalls
- worldwide

###  other available R packages or routines that could help for code development

unknown for the moment

**Comment by Jo-Schie** [comment]
Hi Melvin. So would the indicator be "Sum of CO2 emissions in megatons per AOI over a given period of time?" 

How do you deal with the issue of wind? Do winds influence this variable or what other empirical issues do you see? Should they be accounted for in the routine or do you suggest to have simple zonal statistics?

**Comment by melvinhlwong** [comment]
Exactly. Mean or sum of CO2 over AoI. I would not go about the issue of wind but draw big AoI in this case for simple zonal statistics. 

The most critical point at this stage is
- [ ] Feedback from Heike if she as user would see benefits (planned on May 02)
- [ ] Feedback from other experts on their opinion (e.g. Jochen H on atmospheric CO2)
- [ ] Check spatial resolution of xCO2

**Comment by Jo-Schie** [comment]
I will temporarly close this issue as "not currently planned". We can reopen when we start to work on it. I also created an overview page of all potentially new indicators [here](https://github.com/mapme-initiative/mapme.biodiversity/wiki/List-of-potentially-new-Indicators).
