### ISSUE TITLE
Test errors in reverse dependency checks with GDAL 3.4.3 and 3.5.0RC1

### ISSUE THREAD

**Issue by rsbivand** [mapme-initiative/mapme.biodiversity#65]
[testthat.Rout.zip](https://github.com/mapme-initiative/mapme.biodiversity/files/8647347/testthat.Rout.zip)
This file details errors in test output which is for GDAL 3.5.0RC1 and released **sf** 1.0-7. The problems persist with **sf** main branch head and GDAL 3.5.0RC1 or GDAL 3.4.3.

Some tests fail on CRAN, but you seem to skip CRAN checks - this is unhelpful for all non-CRAN reverse development checks. Unit tests should pass on a standard installation, otherwise they generate unneeded work when checking reverse dependencies. There are now > 1100 packages to check.

**Comment by goergen95** [comment]
Thanks! We test the package on a selection of standard installations via [GitHub Actions](https://github.com/mapme-initiative/mapme.biodiversity/actions) where we don't see these errors. However, with [162bf79](https://github.com/mapme-initiative/mapme.biodiversity/commit/162bf79ce52974a7a6139e19e57bc51aa6f97ec2) I removed a number of tests that require internet resources until I figure out a way how I can reliably test these routines without causing trouble for someone else. These changes will be submitted to CRAN quickly. I hope that will fix the reverse dependency checks for **sf**. I will close for the moment, but feel free to reopen if the issues persist.

**Comment by rsbivand** [comment]
Please reopen until definitely resolved. The window to report GDAL regressions is hours not days.

**Comment by rsbivand** [comment]
GA are never forward-looking, in that they only look backwards to let one track impacts of changes one has made in the specific codebase. Reverse dependency checks are forward-looking where they look for impacts on unchanged codebases of changes in upstream software on which the codebase depends. This is the reason for CRAN checks using R-devel, to see how packages are impacted as R is improved and bugs fixed. So the tests should arguably specify versions of upstream software (R itself, R packages and external libraries these use, often exposed in `*_extSoftVersion()` functions).

With  the tests in this package, nobody  can tell whether a hard test failure is caused by an upstream change from examining the test output.

**Comment by goergen95** [comment]
I revisited the unit tests and removed all the glitter that obscures the output. Could I bother you to run revdep checks against the current head again? This way maybe we can pinpoint what is going on before I'll submit an update to CRAN. Thanks!

**Comment by rsbivand** [comment]
[testthat.Rout.zip](https://github.com/mapme-initiative/mapme.biodiversity/files/8654877/testthat.Rout.zip)
Still 8 probably misleading test failures. My system:
```
> sessionInfo()
R version 4.2.0 (2022-04-22)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Fedora Linux 35 (Workstation Edition)
...
attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] mapme.biodiversity_0.1.2

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.8.3       magrittr_2.0.3     units_0.8-0        tidyselect_1.1.2  
 [5] R6_2.5.1           rlang_1.0.2        fansi_1.0.3        stringr_1.4.0     
 [9] dplyr_1.0.9        tools_4.2.0        grid_4.2.0         data.table_1.14.2 
[13] KernSmooth_2.23-20 utf8_1.2.2         terra_1.5-29       cli_3.3.0         
[17] e1071_1.7-9        DBI_1.1.2          ellipsis_0.3.2     class_7.3-20      
[21] assertthat_0.2.1   tibble_3.1.7       lifecycle_1.0.1    sf_1.0-8          
[25] crayon_1.5.1       tidyr_1.2.0        purrr_0.3.4        codetools_0.2-18  
[29] vctrs_0.4.1        glue_1.6.2         stringi_1.7.6      proxy_0.4-26      
[33] compiler_4.2.0     pillar_1.7.0       generics_0.1.2     classInt_0.4-3    
[37] pkgconfig_2.0.3   
```

**Comment by goergen95** [comment]
I think I pinpointed these errors to some changes how **terra_1.5-29** structures the output of `terra::zonal()` when NA or NaN values are present in the respective raster. We use `zonal()` as an engine in quite a few routines. I will fix these in the coming days. Thank you very much for pointing this out.

**Comment by rsbivand** [comment]
Yes, with released **terra**, the tests pass. Maybe you could explore CI with the development version of **terra**, or simply clone **terra** and run on local install? Useful to know that this failure isn't caused by the new GDAL version.

**Comment by goergen95** [comment]
Agreed! Specifically, I would suggest to test against both, development versions of **sf** and **terra** as these are the packages's "main" dependencies when it comes to spatial processing. By any chance, are you aware of another packages that uses such a CI that I can use as a blueprint?

**Comment by goergen95** [comment]
I included a job in GA that runs on the latest heads of **sf** and **terra** that now checkout fine. Since it runs in ubuntu-latest GDAL 3.0.4 is installed. For the future we could try to include a more recent GDAL version.
