### ISSUE TITLE
Add engine-choice as a standard functionality to all indicator calc functions

### ISSUE THREAD

**Issue by Jo-Schie** [mapme-initiative/mapme.biodiversity#69]
@Ohm-Np  masters thesis will show that choosing the right processing strategy for big geospatial data analysis in R depends amongst others on the spatial resolution of the data and the amount of features to be processed. Different packages, particularly `terra` and `exactextract` perform differently in different settings, and it is desirable to have the flexibility to choose the best function for a specific task (in addition to being able to parallelize the processing, as our package currently already allows). 

So my suggestion is to create a standardized "engine chooser function" that allows people to choose e.g. between `terra zonal`, `terrax extract` and `exact extract`. Similarly, it could be possible to implement this for vector data, letting people choose between `terra intersection` and `sf intersection`. However, that would be probably more difficult since both work with different object classes. Maybe despite the knowledge that Om's thesis is creating around big data analysis, this could be a central contribution from his thesis to the package. 

fyi: @goergen95

**Comment by Ohm-Np** [comment]
Here's a small reprex showing use of - `zonal` vs `terra::extract` -  for computation of areal statistics:

```r

## load sample datasets
library(terra)
rc <- rast("../../Om/test/classified_2000.tif")
roi <- vect("../../Om/test/roi_grids.gpkg")

## area raster
crop <- terra::crop(rc, roi[1, ])
mask <- terra::mask(crop, roi[1, ])
area <- terra::cellSize(mask, unit = "km")

## area of a single aoi
terra::expanse(roi[1, ], "km")
# [1] 4.988084
```
_**Note** The values 0 and 1 in column max indicates whether the polygon is affected or not by hurricane & raster resolution is ~111 m._

![masked_roi](https://user-images.githubusercontent.com/56826085/172374080-b21931c9-f55d-4783-95e4-f962f105c8c0.jpeg)

The result from `patches_zonal` indicates area with values 0 and 1, however, the sum of the both areas seem to exceed the area of polygon by ~0.5 sqkm which is much off considering the accuracy.

```r
## zonal
patches_zonal <- terra::zonal(area, mask, "sum")
patches_zonal

#   max     area
# 1   0 1.189579
# 2   1 4.384729
```
In case of `patches_terra` we only get the overall area of the raster intersected by polygon, but we can not get areal statistics directly (for values `0` & `1`) as in zonal. 
``` r
## terra extract on area raster
patches_terra <- terra::extract(area, roi[1, ], sum)
patches_terra

# ID     area
# 1  1 4.962497
```

The probable workaround to get area from `terra::extract` is to divide the total area by the number of cells  - and - multiply by the number of cells for the particular values.
```r
## terra extract on mask layer
mask_terra <- terra::extract(mask, roi[1, ])
aggregate(. ~ max, data = mask_terra, FUN = sum)

# max  ID
# 1   0  86
# 2   1 352

area_of_polygon = 4.988084
ncells = 86 + 352
area_per_cell <- area_of_polygon/ncells

area_values_0 <- area_per_cell * 86
area_values_0
# 0.9793955

area_values_1 <- area_per_cell * 352
area_values_1
# 4.008689

area_values_0 + area_values_1
# 4.988084 
```

So, I think the use of engine choices also depends on the complexity of the codes/routines.

**PS: I am not sure if we have much easier way to compute areal stats using `terra::extract`.**

**Comment by goergen95** [comment]
It would be more helpful if examples like above include data we all have access to. 

The current way how the different engines are implemented is shown with the example below. As we can see, there seems to be no difference in the area estimates between the two options using terra and only a slight difference using exactextractr. In my view it boils down to a performance question, that is which implementation is the fastest. Please also note that this is only an area estimation because the original data is **unprojected**. Again, this is a trade-off between accuracy and performance.

``` r
library(mapme.biodiversity)
library(sf)
#> Linking to GEOS 3.10.1, GDAL 3.4.0, PROJ 8.2.0; sf_use_s2() is TRUE
library(terra)
#> terra 1.5.30
library(exactextractr)
library(tibble)

clay <- system.file("res", "soilgrids", "clay_0-5cm_mean.tif", 
                        package = "mapme.biodiversity") |>
  rast()
aoi <- system.file("extdata", "sierra_de_neiba_478140_2.gpkg",
                   package = "mapme.biodiversity")

# slightly different area estimates between sf and terra for unprojected geometries
aoi_sf <- read_sf(aoi)
st_area(aoi_sf) 
#> 183491611 [m^2]

aoi_terra <- vect(aoi)
expanse(aoi_terra)
#> [1] 182921585

# retrieve areal statistics using terra::extract
clay_binary <- clay < 350
area <- cellSize(clay, unit = "m")
(result_extract <- extract(area * clay_binary, aoi_terra, sum))
#>   ID     area
#> 1  1 94329419

# retrive areal statistics via terra::zonal
aoi_zone <- rasterize(aoi_terra, clay)
(result_zonal <- zonal(area * clay_binary, aoi_zone, sum))
#>   layer     area
#> 1     1 94329419

# retrieve areal statistics via exactextractr:exact_extract
(result_exact <- exact_extract(area * clay_binary, aoi_sf, "sum"))
#> [1] 94455208


# calculate difference in percent
result_zonal$area / result_exact * 100
#> [1] 99.86683
```

<sup>Created on 2022-06-11 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by Jo-Schie** [comment]
Thanks to both of you for your examples. @goergen95 : your example most probably does not show considerable differences because your AOI is rather big (183.492  sqkm) with a small raster as input (see also my [issue](https://github.com/mapme-initiative/mapme.biodiversity/issues/72) about this). So it's not purely about performances when having edge cases (small AOIs or coarse raster resolutions). Not sure how exact extract does it though to get more proximate to the real area...

**Comment by Ohm-Np** [comment]
The original extent of raster and polygon:
![crop_raster](https://user-images.githubusercontent.com/56826085/184373031-c2a1dbee-f620-407f-b458-da971d23290b.jpg)

How terra functions work:
![mask_raster](https://user-images.githubusercontent.com/56826085/184373075-4737ef6c-056e-4f9d-a020-3da422fd6e2e.jpg)

How exactextractr works:
![mask_rasterExact](https://user-images.githubusercontent.com/56826085/184372815-f020cd72-395b-411b-b1eb-f2ba1964e3fc.jpg)

**Comment by Ohm-Np** [comment]
Status of **_engine choices_** availability in current raster calc. functions:
|SN|Indicator|Engine-choice|
|---|----------|---------------|
|1|drought_indicator|Yes|
|2|elevation|Yes|
|3|tri|Yes|
|4|population_count|Yes|
|5|precipitation_chirps|Yes|
|6|precipitation_wc|Yes|
|7|soilproperties|Yes|
|8|temperature_max_wc|Yes|
|9|temperature_min_wc|Yes|
|10|traveltime|Yes|
|11|Landcover|No|
|12|treecover_area|No|
|13|treecover_area_and_emissions|No|
|14|treecoverloss_emissions|No|

**Comment by Jo-Schie** [comment]
> original extent 	how terra works 	how exactextractr works
> ![crop_raster](https://user-images.githubusercontent.com/56826085/184373031-c2a1dbee-f620-407f-b458-da971d23290b.jpg) 	![mask_raster](https://user-images.githubusercontent.com/56826085/184373075-4737ef6c-056e-4f9d-a020-3da422fd6e2e.jpg) 	![mask_rasterExact](https://user-images.githubusercontent.com/56826085/184372815-f020cd72-395b-411b-b1eb-f2ba1964e3fc.jpg)

Is there a difference between terra extract and terra zonal?

**Comment by Ohm-Np** [comment]
> Is there a difference between terra extract and terra zonal?

Both the terra extract and terra zonal follow the same approach.
