### ISSUE TITLE
broken download link - traveltime (accessibility)

### ISSUE THREAD

**Issue by Ohm-Np** [mapme-initiative/mapme.biodiversity#74]
The link to download accessibility rasters in the package seem to be broken. However, downloading the rasters manually using the same link through PC works.

```r
# Error: [rast] cannot open file: ../../datalake/tempdir//traveltime/traveltime-20k_50k.tif
# In addition: Warning message:
# ../../datalake/tempdir//traveltime/traveltime-20k_50k.tif: No such file or directory (GDAL error 4) 
```

[Link to source](https://figshare.com/articles/dataset/Travel_time_to_cities_and_ports_in_the_year_2015/7638134/3)

**Comment by Ohm-Np** [comment]
|old_url|new_url|
|---|---|
|`https://ndownloader.figshare.com/files/index`|`https://figshare.com/ndownloader/files/index`|

**Comment by Ohm-Np** [comment]
solved!

**Comment by goergen95** [comment]
I cannot reproduce this. For me the old_url still works as expected.

**Comment by Ohm-Np** [comment]
To be able to download the resource, I change the url and also this portion of the script: 

![Screenshot 2022-06-22 121758](https://user-images.githubusercontent.com/56826085/175005698-db3dfc49-3315-48f2-be9e-0318044e6835.jpg)

The problem was perhaps, it was considering the normal get routines as part of testing. Now it's working fine!
