### ISSUE TITLE
Make people aware that downloaded data might not match portfolio if spatial extent of AOIs was changed. 

### ISSUE THREAD

**Issue by Jo-Schie** [mapme-initiative/mapme.biodiversity#83]
Currently the download function only checks whether there is already a folder with user data but it does not check whether data inside matches the actual portfolio. That can become quickly a problem if a user e.g. loads two different datasets (AOIs) and then downloads twice the data. Best fix would be, of course, to automatically check inside the folder, whether the extents match but that takes probably quite some time to implement. So as a quick fix i would suggest to replace messages like

_"The following requested resources are already available: treecover2000, lossyear, greenhouse."_

with a message like:

_"The following requested resources are already available: treecover2000, lossyear, greenhouse in folder xyz. If you changed the spatial AOI please make sure to delete those folders first before downloading the data. If the spatial extent of your AOIs did not change, you may proceed processing the data."_

**Comment by goergen95** [comment]
Please see the discussion in #130. Except for soilgrid ressource, we actually check if all required files are available, given that `add_resources` was set to FALSE. I am thus closing in favor of #92 and #91, which also touch on this topic.
