### ISSUE TITLE
Add feature that allows users to choose their own data-input path or url. 

### ISSUE THREAD

**Issue by Jo-Schie** [mapme-initiative/mapme.biodiversity#89]
I think it could be very desirable to allow users to input their own data. This is especially relevant for data where basically one big file is downloaded once (e.g. accessibility data) and no continous updates are provided. In that case it could be very desirable for us to e.g. store that data in a local database and then reuse it. Like this users behind a firewall which may block some of the urls might also use the package.

**Comment by goergen95** [comment]
What do you mean by "local database" and in what sense would this feature differ from the current behavior?

**Comment by Jo-Schie** [comment]
I could download the data myself, store it eg in a Postgres database and then just plug it into the function... or is that already possible?

**Comment by goergen95** [comment]
Definitely not possible and also not easy to implement as we would have to design a new interface for database I/O. Downloading data yourself, naming files as expected by the package and store them locally is error-prone but generally possible right now.

**Comment by goergen95** [comment]
The ideas raised here are still relevant. I am still closing it in favor of #92. Let's continue the discussion there an see how we can support users to bring their own data.
