### ISSUE TITLE
Complete init_portfolio() documentation 

### ISSUE THREAD

**Issue by fBedecarrats** [mapme-initiative/mapme.biodiversity#91]
The package is a wonder, saves a lot of time and streamlines the data preparation workflow. The documentation is generally very good. 
While using it, I realize that there are a few aspects that I didn't understand initially. I'm mentioning them here because I think further explanations in the package documentation might help newcomers: 
- The role of the tmp directory was not clear for me and it appears that issues can arise regarding writing rights on the selected folders (cf. #90). I suggest to add an explanation on its role in the init_portfolio() function documentation, and suggest to keep the default folder.
- The possibility to use ariabin seems attractive but I do not understand how to do it. Further explanation would be useful.
- I found the wording on the add_resource argument confusing. After reading it I could not figure out if I should turn it to TRUE or FALSE to use resources I had already downloaded. I think it would be useful to rephrase the corresponding paragraph. It would be useful to specify that resources are only scanned when running the function. Adding new resources later on does not update the resource index in the portfolio object (see #92 ).

**Comment by goergen95** [comment]
with release 0.6.0 `init_portfolio()` was deprecated in favor of `mapme_options()`, thus closing here.
