### ISSUE TITLE
Update documentation or source for SoilGrids

### ISSUE THREAD

**Issue by fBedecarrats** [mapme-initiative/mapme.biodiversity#99]
Hi there!
I was reviewing the soilgrids indicators. The [function documentation](https://mapme-initiative.github.io/mapme.biodiversity/reference/soilgrids.html) refers to the [2017 PLOS One paper](https://soil.copernicus.org/articles/7/217/2021/#Ch1.T6), which corresponds to a ~60% accuracy. The new generation of SoilGrids displays an accuracy > 90% and there is a corresponding publication in [the SOIL journal](https://soil.copernicus.org/articles/7/217/2021/#Ch1.T6).
Is it possible to ensure that the mapme.biodiversity packages fetches its data from the 2.0 version of SoilGrid, and refer to the 2021 paper, that includes an updated information?
Best regards,
FB
PS : there is a typo at the beginning of the function documentation: it should read "each parameter is mapped" (currently it reads "each parapeter**s** is mapped")

**Comment by goergen95** [comment]
The URL points towards the latest release, see:
https://github.com/mapme-initiative/mapme.biodiversity/blob/72ae9fa65218febf4146d269e11d6d0f0ef9fb3b/R/get_soilgrids.R#L147

If I understand the [README.md](https://files.isric.org/soilgrids/latest/data/README.md) correctly, this points towards v2.0. So only the documentations needs some changes.

**Comment by fBedecarrats** [comment]
Hi there,
I understand too that it refers to the 2.0 version to soilgrids. Then my suggestion would be to update the "reference" section of [the soilgrids function documentation](https://files.isric.org/soilgrids/latest/data/) to point to the SOIL paper instead of the PLOS ONE paper.
